/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rain;

import javax.swing.JOptionPane;

/**
 *
 * @author Rei
 */
public class RPS extends javax.swing.JFrame {

    /**
     * Creates new form RPS
     */
    public RPS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSC1 = new javax.swing.JTextField();
        txtHP1 = new javax.swing.JTextField();
        txtHP2 = new javax.swing.JTextField();
        txtSC2 = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();
        btnTutorial = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtP1 = new javax.swing.JPasswordField();
        txtP2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 200));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Rock Paper Scissors");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("PLAYER 1");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PLAYER 2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("HEALTH");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("SCORE");

        txtSC1.setEditable(false);
        txtSC1.setText("0");

        txtHP1.setEditable(false);
        txtHP1.setText("5");

        txtHP2.setEditable(false);
        txtHP2.setText("5");

        txtSC2.setEditable(false);
        txtSC2.setText("0");

        btnPlay.setText("Versus");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnTutorial.setText("Tutorial");
        btnTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutorialActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtHP2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSC2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtHP1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSC1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(btnPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTutorial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        int P1 = Integer.parseInt(txtP1.getText());
        int P2 = Integer.parseInt(txtP2.getText());
        int HP1 = Integer.parseInt(txtHP1.getText());
        int HP2 = Integer.parseInt(txtHP2.getText());
        int SC1 = Integer.parseInt(txtSC1.getText());
        int SC2 = Integer.parseInt(txtSC2.getText());
        String HP = "";
        String SC = "";
        
        if (P1 == 1 && P2==1){
            JOptionPane.showMessageDialog(null, "Both player's chose the same acion. Round ended in a draw", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        } else if (P1==1 && P2==2){
            HP1 -=1;
            HP = String.valueOf(HP1);
            SC2 += 1;
            SC = String.valueOf(SC2);
            txtHP1.setText(HP);
            txtSC2.setText(SC);
            JOptionPane.showMessageDialog(null, "Player 1 chose: Rock \n Player 2 chose: Paper \n Summary: Player 2 wins!", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        } else if (P1==1 && P2==3){
            HP2 -=1;
            HP = String.valueOf(HP2);
            SC1 += 1;
            SC = String.valueOf(SC1);
            txtHP2.setText(HP);
            txtSC1.setText(SC);
            JOptionPane.showMessageDialog(null, "Player 1 chose: Rock \n Player 2 chose: Scissors \n Summary: Player 1 wins!", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        } else if (P1==2 && P2==1){
            HP2 -=1;
            HP = String.valueOf(HP2);
            SC1 += 1;
            SC = String.valueOf(SC1);
            txtHP2.setText(HP);
            txtSC1.setText(SC);
            JOptionPane.showMessageDialog(null, "Player 1 chose: Paper \n Player 2 chose: Rock \n Summary: Player 1 wins!", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        } else if (P1==2 && P2==2){
            JOptionPane.showMessageDialog(null, "Both player's chose the same acion. Round ended in a draw", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        } else if (P1==2 && P2==3){
            HP1 -=1;
            HP = String.valueOf(HP1);
            SC2 += 1;
            SC = String.valueOf(SC2);
            txtHP1.setText(HP);
            txtSC2.setText(SC);
            JOptionPane.showMessageDialog(null, "Player 1 chose: Paper \n Player 2 chose: Scissors \n Summary: Player 1 wins!", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        }else if (P1==3 && P2==1){
            HP1 -=1;
            HP = String.valueOf(HP1);
            SC2 += 1;
            SC = String.valueOf(SC2);
            txtHP1.setText(HP);
            txtSC2.setText(SC);
            JOptionPane.showMessageDialog(null, "Player 1 chose: Rock \n Player 2 chose: Scissors \n Summary: Player 1 wins!", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        }else if (P1==3 && P2==2){
            HP2 -=1;
            HP = String.valueOf(HP2);
            SC1 += 1;
            SC = String.valueOf(SC1);
            txtHP2.setText(HP);
            txtSC1.setText(SC);
            JOptionPane.showMessageDialog(null, "Player 1 chose: Rock \n Player 2 chose: Scissors \n Summary: Player 1 wins!", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        } else if (P1==3 && P2==3){
            JOptionPane.showMessageDialog(null, "Both player's chose the same acion. Round ended in a draw", "Round Summary", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid option was given", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        
        if (HP1 == 0){
            txtHP1.setText("5");
            txtHP2.setText("5");
            JOptionPane.showMessageDialog(null, "Player 2 WINS!!!", "Match Ended", JOptionPane.INFORMATION_MESSAGE);
        } else if (HP2==0){
            txtHP1.setText("5");
            txtHP2.setText("5");
            JOptionPane.showMessageDialog(null, "Player 1 WINS!!!", "Match Ended", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutorialActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RPSTutorial().show(true);
    }//GEN-LAST:event_btnTutorialActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtHP1.setText("5");
        txtHP2.setText("5");
        txtSC1.setText("0");
        txtSC2.setText("0");
        txtP1.setText("");
        txtP2.setText("");
    }//GEN-LAST:event_btnResetActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTutorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtHP1;
    private javax.swing.JTextField txtHP2;
    private javax.swing.JPasswordField txtP1;
    private javax.swing.JPasswordField txtP2;
    private javax.swing.JTextField txtSC1;
    private javax.swing.JTextField txtSC2;
    // End of variables declaration//GEN-END:variables
}
